branchName: short
autoCloseIssue: true
branches:
  - label: docs
    prefix: docs/
  - label: bug🐛
    prefix: bug/
  - label: etc
    prefix: etc/
  - label: refactor
    prefix: refactor/
  - label: style
    prefix: style/
  - label: '*'
    prefix: feat/
commentMessage: 'Branch ${branchName} created for issue: ${issue.title}'
copyIssueDescriptionToPR: true
트copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
copyIssueMilestoneToPR: true
